import type { Metadata } from 'next';
import './globals.css';
import { GeistMono } from 'geist/font/mono';
import PowWrapper from '~/components/pow-wrapper';

export const metadata: Metadata = {
    title: 'pow',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={GeistMono.variable}>
            <body className="bg-primary-200 font-mono antialiased">
                <PowWrapper>{children}</PowWrapper>
            </body>
        </html>
    );
}
