import type { Metadata } from 'next';
import './globals.css';
import { GeistMono } from 'geist/font/mono';
import PowWrapper from '~/components/pow-wrapper';
import { PropsWithChildren } from 'react';

export const metadata: Metadata = {
    title: 'pow',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
    return (
        <html lang="en" className={GeistMono.variable}>
            <body className="bg-primary-200 font-mono antialiased">
                <PowWrapper>{children}</PowWrapper>
            </body>
        </html>
    );
}
